services:
  health-tracker:
    build:
      context: .
    container_name: health-tracker-app
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_PATH: /app/data/health_tracker.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped
