version: '3.8'
services:
  health-tracker:
    build: .
    container_name: health-tracker-app
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
